baseURL = "http://cohelet.click/"
languageCode = "de-de"
defaultContentLanguage = "de-de"
title = "Cohelet Space – Coworking in Görlitz"
theme = "hello-friend-ng"

[params]
description = "Coworking Space mit 4 Schreibtischen, ruhig, klein, familiär"
contactEmail = "cohelet.space@proton.me"
contactPhone = "+49 123 4567890"
address = "Parsevalstr. 7, 02826 Görlitz"
openingHours = "7:00–22:00"
dayPrice = 15
monthPrice = 200
wifi = true
coffee = true
printer = true
meetingRoom = true

# Banner / Header
banner = "images/banner.jpg"   # unter /static/images/banner.jpg ablegen

# Favicon (optional)
[params.favicon]
icon = "images/favicon.png"
mask = true

# Kontaktformular
contact_service = "formspree"  # "netlify", "formspree" oder "php"
contact_formspree_id = "xdklozay"       # falls Formspree genutzt wird

[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Über uns"
  url = "/about"
  weight = 2
  
  [[menu.main]]
  name = "Stipendien"
  url = "/stipendium"
  weight = 3

  [[menu.main]]
  name = "Kontakt"
  url = "/kontakt"
  weight = 4
  
  [params.footer]
  trademark = "Cohelet Coworking Büro Görlitz"
  author = "Jens Borrack"
  copyright = "Alle Rechte vorbehalten"
  rss = false

[markup]
  [markup.goldmark.renderer]
  unsafe = true

